src/Entity/Quizz.php
<?php

namespace App\Entity;

use App\Repository\QuizzRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuizzRepository::class)
 */
class Quizz
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $Utilisateur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_quizz;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif_desactive;

    /**
     * @ORM\OneToMany(targetEntity=Question::class, mappedBy="Quizz")
     */
    private $questions;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
    }
    public function __toString(){
        return $this->titre_quizz;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(?Utilisateur $Utilisateur): self
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }

    public function getTitreQuizz(): ?string
    {
        return $this->titre_quizz;
    }

    public function setTitreQuizz(string $titre_quizz): self
    {
        $this->titre_quizz = $titre_quizz;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getActifDesactive(): ?bool
    {
        return $this->actif_desactive;
    }

    public function setActifDesactive(bool $actif_desactive): self
    {
        $this->actif_desactive = $actif_desactive;

        return $this;
    }

    /**
     * @return Collection|Question[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setQuizz($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->contains($question)) {
            $this->questions->removeElement($question);
            // set the owning side to null (unless already changed)
            if ($question->getQuizz() === $this) {
                $question->setQuizz(null);
            }
        }

        return $this;
    }
}

src/Form/QuizzType.php
<?php

namespace App\Form;

use App\Entity\Quizz;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuizzType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre_quizz')
            ->add('actif_desactive')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Quizz::class,
        ]);
    }
}

src/Controller/QuizzController.php
<?php

namespace App\Controller;

use App\Entity\Quizz;
use App\Form\QuizzType;
use App\Repository\QuizzRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/quizz")
 */
class QuizzController extends AbstractController
{
    /**
     * @Route("/", name="quizz_index", methods={"GET"})
     * @param QuizzRepository $quizzRepository
     * @return Response
     */
    public function index(QuizzRepository $quizzRepository): Response
    {
        return $this->render('quizz/index.html.twig', [
            'quizzes' => $quizzRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="quizz_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $quizz = new Quizz();
        $form = $this->createForm(QuizzType::class, $quizz);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quizz->setDateCreation(new \DateTime("now"));
            $quizz->setUtilisateur($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($quizz);
            $entityManager->flush();

            return $this->redirectToRoute('quizz_index');
        }

        return $this->render('quizz/new.html.twig', [
            'quizz' => $quizz,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="quizz_show", methods={"GET"})
     * @param Quizz $quizz
     * @return Response
     */
    public function show(Quizz $quizz): Response
    {
        return $this->render('quizz/show.html.twig', [
            'quizz' => $quizz,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="quizz_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Quizz $quizz
     * @return Response
     */
    public function edit(Request $request, Quizz $quizz): Response
    {
        $form = $this->createForm(QuizzType::class, $quizz);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('quizz_index');
        }

        return $this->render('quizz/edit.html.twig', [
            'quizz' => $quizz,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="quizz_delete", methods={"DELETE"})
     * @param Request $request
     * @param Quizz $quizz
     * @return Response
     */
    public function delete(Request $request, Quizz $quizz): Response
    {
        if ($this->isCsrfTokenValid('delete'.$quizz->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($quizz);
            $entityManager->flush();
        }

        return $this->redirectToRoute('quizz_index');
    }
}

templates/quizz/_delete_form.html.twig
<form method="post" action="{{ path('quizz_delete', {'id': quizz.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quizz.id) }}">
    <button class="btn">Delete</button>
</form>

templates/quizz/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/quizz/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quizz{% endblock %}

{% block body %}
    <h1>Edit Quizz</h1>

    {{ include('quizz/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('quizz_index') }}">back to list</a>

    {{ include('quizz/_delete_form.html.twig') }}
{% endblock %}

templates/quizz/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des quizz{% endblock %}

{% block body %}

{% include 'navbar.html.twig' %}

    <div class="container">

    <h2 id="hDeuxQuizzHisto">Mes QuizZaNou ( {{ quizzes|length }} )</h2>

        {% for quizz in quizzes %}
            <div id="lignePleine">
                <div id="bloc1">
                    <div id="titreQuizz">{{ quizz.titreQuizz }}</div>
                    <div id="nbQuestions">{{ quizz.questions|length }} question{% if quizz.questions|length > 1 %}s{% endif %}</div>
                    <div class="crud" id="statResp"><a id="stat" href="{{ path('quizz_show', {'id': quizz.id}) }}">Statistiques</a></div>
                </div>
                <div id="bloc2">
                    <div class="displayCrud">
                        <div class="crud" id="testResp"><a id="test" href="{{ path('quizz_show', {'id': quizz.id}) }}">Tester</a></div>
                        <div class="crud" id="jouResp"><a id="jou" href="{{ path('quizz_show', {'id': quizz.id}) }}">Voir</a></div>
                    </div>
                    <div class="displayCrud">
                        <div class="crud" id="editResp"><a id="edit" href="{{ path('quizz_edit', {'id': quizz.id}) }}">Editer</a></div>
                        <div class="crud" id="supResp"><a id="sup" href="{{ path('quizz_delete', {'id': quizz.id}) }}">Supprimer</a></div>
                    </div>
                </div>
            </div>
        {% else %}
            <tr>
                <td colspan="5">Enregistrements non trouvés</td>
            </tr>
        {% endfor %}

    </div>

{% endblock %}

templates/quizz/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création Quizz{% endblock %}

{% block body %}
    
{% include "navbar.html.twig" %}
  
  <div id="containerBody">
    
    <div id ="sideBar">
      <h3>QuizZaNou en cours</h3>
    
      <div id="">
      
      </div>

      <div id="bouttonSibar">
        <input type="button" value="Ajouter une question">
        <input type="button" value="Valider le questionnaire">
      </div>
    </div>{# end div sidebar #}

    {# début du contenu pour la création d'une question #}
    <div id="containerMain">
  
    {{ include('quizz/_form.html.twig') }}
    
    </div>{# end div containerMain #}

    <a href="{{ path('quizz_index') }}" style="color: black">Voir la liste des quizz</a>
  </div>{# end div container body #}
    {% endblock %}

templates/quizz/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quizz{% endblock %}

{% block body %}
    <h1>Quizz</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ quizz.id }}</td>
            </tr>
            <tr>
                <th>Titre_quizz</th>
                <td>{{ quizz.titreQuizz }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ quizz.dateCreation ? quizz.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Actif_desactive</th>
                <td>{{ quizz.actifDesactive ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <ul>
{% for question in quizz.questions %}

    <li>{{ question.intitule }} <a href="{{ path('question_edit', {'id': question.id}) }}" style="color: black;">Modifier</a></li>

{% endfor %}
</ul>
    
    <a href="{{ path('question_new', {"id":quizz.id}) }}" style="color:black">Ajouter une question</a>
    
    <a href="{{ path('quizz_index') }}">back to list</a>

    <a href="{{ path('quizz_edit', {'id': quizz.id}) }}">edit</a>

    {{ include('quizz/_delete_form.html.twig') }}
{% endblock %}